### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Flaiers** [dancaron/Django-ORM#9]
HI. What is the meaning of this project? The user can install Django himself and remove some lines, it will take 3 minutes. I think if you do it in the form of a pip package and simplify the methods, it will be more attractive!

**Comment by Flaiers** [comment]
pip install ... a couple of seconds and you're done

**Comment by Andrew-Chen-Wang** [comment]
A pip package might not be good contextually tho. What would work better is a cookiecutter project
